### ISSUE TITLE
error with terraform v0.12

### ISSUE THREAD

**Issue by Arnold1** [danmrichards/terraform-sandbox#1]
hi,

can you help me to get it working with terraform v0.12 (latest version)?
```
main.go:16:2: module github.com/hashicorp/terraform@latest found (v0.12.26), but does not contain package github.com/hashicorp/terraform/config/module
```

if I remove that package I get:
```
# go build main.go
# github.com/terraform-providers/terraform-provider-google/google
/go/pkg/mod/github.com/terraform-providers/terraform-provider-google@v0.0.0-20190430222256-f9a9636be7cd/google/resource_sql_database_instance.go:528:50: too many arguments in call to config.clientSqlAdmin.Users.Delete
        have (string, string, string, string)
        want (string, string)
/go/pkg/mod/github.com/terraform-providers/terraform-provider-google@v0.0.0-20190430222256-f9a9636be7cd/google/resource_sql_user.go:174:48: too many arguments in call to config.clientSqlAdmin.Users.Update
        have (string, string, string, *sqladmin.User)
        want (string, string, *sqladmin.User)
/go/pkg/mod/github.com/terraform-providers/terraform-provider-google@v0.0.0-20190430222256-f9a9636be7cd/google/resource_sql_user.go:212:47: too many arguments in call to config.clientSqlAdmin.Users.Delete
        have (string, string, string, string)
        want (string, string)
```
